version: '3.1'

services:

  db:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 12000:3306
