# Use root/example as user/password credentials
version: '3.1'

services:
    mariadb:
        image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: "mariadb"
          MYSQL_USER: "user"
          MYSQL_PASSWORD: "password"

